# Generated by Django 3.1.7 on 2021-03-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='publications',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='publicationsimages',
            old_name='publications',
            new_name='publication',
        ),
    ]
